### ISSUE TITLE
Accidental removal of supervisor3 and kafka_protocol as application

### ISSUE THREAD

**Issue by tudborg** [kafka4beam/brod#146]
20c0ca8abb260533572ce0131a9e01c544a8bdef removed supervisor3 and kafka_protocol from the list of `applications` in `brod.app.src`.

It seems they should either be in `applications` or `included_applications`.
I'm guessing accidental removal? :)

cc @zmstone

**Comment by zmstone** [comment]
Hi @tbug. 
That was intentional change.

`supervisor3` and `kafka_protocol` are both static libraries,
there is no need to start these two applications before starting `brod`.
(i.e. `brod:start()` would return error otherwise).

The code dependencies are specified in `Makefile` for erlang.mk
and in `rebar.config` for rebar and rebar3.

Is it `reltool` or `relx` who doesn't include those two applications in release?
(it's the only possible impact I can think of).
If that's the case, I guess you can add them explicitly to release tool config file as a workaround for now.

**Comment by tudborg** [comment]
Yea, `relx` exactly :)
I've already added them explicitly to the release, so no worries.
It just took me by surprise when upgrading from 2.1.8, and since the README didn't mention it, I figured the intended change was to move them to `included_applications`, and the removal was accidental.

**Comment by tudborg** [comment]
I pitched this by @jlouis who told me that `included_applications` is the wrong place to put it,
and that they instead should go in `applications`.
My bad :)

**Comment by zmstone** [comment]
right, it only makes senescence to add kafka_protocol as included application because we don't expect anyone else to include it, supervisor3 however is 'too common' in this sense 

i'll add them back to applications
