### ISSUE TITLE
track consumer lag?

### ISSUE THREAD

**Issue by clofresh** [kafka4beam/brod#148]
Is there way to track the consumer lag? Consumer responses tell you the offset high watermark, so you can subtract the that by the current offset you've seen to determine how far behind you are.

**Comment by zmstone** [comment]
yes for partition subscribers, no for topic/group subscribers.
because hw-offset is at message-set level, but topic/group subscribers are implemented to handle messages (not sets).

worth mentioning that if your messages are very small-sized, topic/group subscribers may not work very we'll due to the per-message callback and erlang-message passing overheads

we are working on a handle_message_set (optional in 2.2) behaviour callback for topic/group subscribers.

**Comment by id** [comment]
@clofresh you can take a look at how we implemented this in an external application: https://github.com/klarna/kastlex/blob/master/lib/kastlex/cg_status_collector.ex

**Comment by zmstone** [comment]
`cg_status_collector` in kastlex collects ALL consumer group lags.
The hw-offset in fetched message-set should be enough if you only care about the lagging of current consumer (which may not be a group subscriber)

**Comment by clofresh** [comment]
ok, thanks for the info!
