### ISSUE TITLE
Handle error in brod_group_coordinator commit_offsets

### ISSUE THREAD

**Issue by MikhailKalashnikov** [kafka4beam/brod#150]
In brod_group_coordinator in handle_info(?LO_CMD_COMMIT_OFFSETS and in handle_call(commit_offsets you try to catch throw and stabilize.
But in do_commit_offsets_ you raise exception with erlang:error(EC), but not throw. 
As a result this error is not catched and server crashes without attempt to stabilize.
Is it correct/expected behavior or we should catch this kafka error?

**Comment by zmstone** [comment]
@MikhailKalashnikov this indeed seem like a bug.
which error code was it in your case?

**Comment by MikhailKalashnikov** [comment]
In my case sometimes kafka returns an error UnknownMemberId (by the way, maybe you have seen such error and know how to fix it). 
Since brod_group_coordinator raises it as an error (and not throw) brod_group_coordinator crashes and then a neighbour brod_group_subscriber crashes. 
As a result brod_consumer:maybe_send_fetch_request stops fetching new messages because no subscriber exist.

I've changed erlang:error to erlang:throw in brod_group_coordinator:do_commit_offsets_. And now it works fine for me. I still see the error 'failed to commit offset for topic', but brod does not crash and after 'stabilize' it sends commit again.

**Comment by zmstone** [comment]
do you have a supervisor to restart your subscriber?

when restated, it should rejoin the group and stabilize again. it may take longer than catching the error, but should not stop fetching messages for too long.

**Comment by MikhailKalashnikov** [comment]
I agree that I should add logic to monitor and restart subscriber.
But my question is whether brod_group_coordinator should try to stabilize in case of error first (to do it we should use erlang:throw instead of erlang:error in do_commit_offsets_) or you use erlang:error in do_commit_offsets_ for some reason?

These are my arguments why I think then it can be better to use erlang:throw instead of erlang:error in do_commit_offsets_ and do not crash immediately.

1) I noticed a piece of code in brod_group_coordinator that supposes to handle such error, namely
```
handle_info(?LO_CMD_COMMIT_OFFSETS, #state{is_in_group = true} = State) ->
  {ok, NewState} =
    try
      do_commit_offsets(State)
    catch throw : Reason ->
      stabilize(State, 0, Reason)
    end
```

2) I noticed this comment in brod_group_coordinator - 'let it crash' may not be the optimal strategy...
3) I found that everywhere in brod_group_coordinator you use erlang:throw but not in do_commit_offsets.
4) If we catch an error in brod_group_coordinator and call stabilize then we re-send commit. If brod_group_coordinator crashes and we restart it then we do not commit already processed messages and receive them again. 

So if I am wrong and there is a reason to not catch this error in brod_group_coordinator and crash I will really appreciate if you explain why.

You can see in my fork (https://github.com/MikhailKalashnikov/brod) what change I mean, it is just one line.

 Sorry if I bother you a lot with this question.

**Comment by zmstone** [comment]
Oh, there wasn't any push-back intended to your proposed change. Your arguments make perfect senses.
I was just trying to get more details on the failing scenario, also proposing a workaround before we can fix it.

with regards to the reason why it is an 'error' instead of 'throw': it was more of a 'defensive programming' mind-set, when i don't know how to handle it safely, i crash it. (because there is no message level error code, i.e there could be a partial success for the request)

after reading the code again yesterday, the error codes should perhaps be handled the same as error codes returned in heartbeat response. which is throw-catch then re-stabilize.

Although it's a one line fix, I'd like you to send a pull request.
or if you don't mind to make more changes before sending the pr: create a function to check if all error codes are the same, raise throw if yes, otherwise error.

please pr to branch 'coordinator-handle-commit-offset-error'
