### ISSUE TITLE
when kafka version is 0.10.0.0 and brod send consume protocol in version 0.9 or 0.8, may this cause performance impact?

### ISSUE THREAD

**Issue by theorix** [kafka4beam/brod#158]
description is in 
http://kafka.apache.org/documentation/#upgrade_10_performance_impact

```
The message format in 0.10.0 includes a new timestamp field and uses relative offsets for compressed messages. The on disk message format can be configured through log.message.format.version in the server.properties file. The default on-disk message format is 0.10.0. If a consumer client is on a version before 0.10.0.0, it only understands message formats before 0.10.0. In this case, the broker is able to convert messages from the 0.10.0 format to an earlier format before sending the response to the consumer on an older version. However, the broker can't use zero-copy transfer in this case. Reports from the Kafka community on the performance impact have shown CPU utilization going from 20% before to 100% after an upgrade, which forced an immediate upgrade of all clients to bring performance back to normal. To avoid such message conversion before consumers are upgraded to 0.10.0.0, one can set log.message.format.version to 0.8.2 or 0.9.0 when upgrading the broker to 0.10.0.0. This way, the broker can still use zero-copy transfer to send the data to the old consumers. Once consumers are upgraded, one can change the message format to 0.10.0 on the broker and enjoy the new message format that includes new timestamp and improved compression. The conversion is supported to ensure compatibility and can be useful to support a few apps that have not updated to newer clients yet, but is impractical to support all consumer traffic on even an overprovisioned cluster. Therefore, it is critical to avoid the message conversion as much as possible when brokers have been upgraded but the majority of clients have not.
```

**Comment by zmstone** [comment]
hi @theorix 
we are working on supporting 0.10 protocol.

**Comment by theorix** [comment]
ok，thanks！

**Comment by cdegroot** [comment]
Is there an idea when 0.10 support will be there? We're interested in the max message count parameter in the 0.10 consumer, as we have wildly varying message sizes and this has helped us elsewhere (non-Brod stuff ;-)).

**Comment by zmstone** [comment]
@cdegroot as far as I know, there is no `max message count` notion in kafka protocol.
I'm not sure how other clients did it, but in brod, if you want to avoid fetching too large batches,
just because there are one or two large messages in the stream every once in a while,
you can choose to use a small `max_bytes`, if this number is not big enough to fetch one single message, `brod_consumer' should try fetch exact one message.

**Comment by cdegroot** [comment]
Yup, I'm blabbering nonsense - got confused by the option in the Java client, but on further study it turns out to be a client implementation not a protocol thing. Ignore me :-). 

(we do use the max_bytes to limit batch sizes, but Brod grows that buffer dynamically and doesn't seem to shrink it back fast enough at all times, so we still have issues now and then with too much work being sent to our code in one go; I'm currently "solving" that in Kaffe).

**Comment by zmstone** [comment]
I'm actually working on paramterizing the moving-average window size,
if set window-size to -1, it'll immediately shrink back to original (configured) `max_bytes`.

will be a part of #232
