### ISSUE TITLE
Ability for a client to discover the partitions it is subscribed to

### ISSUE THREAD

**Issue by meadoch1** [kafka4beam/brod#197]
We would like for an instance of our app to be able to discover what partitions it is listening to for a given topic.  We see where the information is stored privately in Brod, but have not found how that information is accessible by the app using Brod.  Is there a way short of implementing the assignments_received callback to get this when the subscriptions are done through start_link_group_subscriber?  We haven't used the assignments_received callback as we want to use the default behavior of the group member and would like to avoid recoding it.

**Comment by zmstone** [comment]
> would like to avoid recoding it

Do you mean you would like to avoid recoding `brod_group_subscriber.erl ` or your callback implementation ?

You don't have to recode `brod_group_sbuscriber` for this.
Instead, you can implement the `assign_partitions` callback (copy from code):
```
%% This function is called only when 'partition_assignment_strategy' is
%% 'callback_implemented' in group config.
%
% commented out as it's an optional callback
%-callback assign_partitions([kafka_group_member()],
%                            [{topic(), partition()}]
%                            cb_state()) -> [{kafka_group_member_id(),
%                                            [brod_partition_assignment()]}].
```

**Comment by zmstone** [comment]
Forgot to mention that this callback is only called for group-leader.
You may implement your own assignment strategy and even do some side-effects like publishing the assignments to external.
Otherwise if you need the followers to aware of the assignments, there is no easy way.

Possible workarounds:
1. Run ad-hock sys:get_state/1 to peek the internals
2. Use tools like https://github.com/klarna/kastlex to fetch offset commit metadata where the group member Erlang node name (plus a timestamp) is available.
3. Implement your own group member.

**Comment by meadoch1** [comment]
Thanks!  This gives me several options to investigate.
