### ISSUE TITLE
Groub subscriber ignores "offset out of range" messages

### ISSUE THREAD

**Issue by cdegroot** [kafka4beam/brod#199]
I'm not sure whether that's a dangerous thing or not. I _think_ that this message should be caught, and solved by fetching the existing offset range (and I guess then either heuristics[1] or a proper crash), and I _think_ that ignoring it is not the correct strategy. Anyway, I'm seeing: 

```erlang
19:15:23.679 [info] group subscriber (groupId=event_ingestion_admin,memberId='event_ingestion_admin@127.0.0.1'/<0.1428.0>-adfe1ca6-b03d-4d9a-88d9-d902a9399db2,generation=2270,pid=#PID<0.1425.0>):
discarded message:{#PID<0.1588.0>,
 {:kafka_fetch_error, "failed_events", 47, :OffsetOutOfRange,
  "The requested offset is not within the range of offsets maintained by the server."}}
```

in the logs of one of our applications - it seems to happen on a series of partitions where, for some reason, '0' has been stored as the current offset fo that group (next up: finding out how that number got in there).

[1] where I would expect something along the lines of "hmm... this offset I have stored doesn't exist anymore - must be that Kafka has purged messages since I went away. Let's request the current lowest offset, if that is larger than my current offset, that's the cause and I can move on after emitting a warning; if my stored offset is higher than the current offset range, though, something is amiss and I should crash"

**Comment by zmstone** [comment]
I agree in some cases crash would be easier to catch attention.
However, in general, since one group subscriber may subscribe to many different topic-partitions,
crashing it will cause a restart then a re-join, which in turn will cause the whole group to
re-balance + partition re-assign, then crash again ... in a dead loop.
Discarding it would at least allow data in other partitions to flow.
(there are lagging monitoring tools etc to alert you if some partition stalls for too long)

Nonetheless, there is a `offset_reset_policy` consumer config.
You may use `reset_to_latest` or `reset_to_earliest`
to make `brod_consumer` automatically reset begin_offset when `OffsetOutOfRange` happens.
This config is by default `reset_by_subscriber` because there is no generically-safe default.

I agree that comparing the committed offset with earliest/latest and be smart about where to start is a nice to have feature,
but I guess committed offset > latest offset only happens when:
a topic is re-created
or,
the client moved from one cluster to another having the exact topic and happen to use the exact group ID.

**Comment by cdegroot** [comment]
Ah, I see it now in the documentation, missed that. Thanks!

**Comment by DEvil0000** [comment]
It happens for example:
If one broker was isolated from the rest (e.g. by network split). If you produce messages to the isolated brokers topic locally and to some other broker for the same topic/partition. After the network split is resolved kafka resolves its split brain by removing the new messages appended on one of both brokers and keeps the messages of the other broker (not sure about the exact logic here). In such cases it happens for me to have high commited offsets and some topic with a lower end of topic/partition offset.

Since we have only two redundant brokers (kafka version 0.9.0.1) in most of our setups and customers like to test redundancy with pulling cables we see this quite often.

**Comment by zmstone** [comment]
@DEvil0000 Yes, but this is only the case when `unclean.leader.election.enable` is set to `true` in broker config.
