### ISSUE TITLE
Efficiently producing to Kafka

### ISSUE THREAD

**Issue by objectuser** [kafka4beam/brod#207]
I'm seeing slow response times producing to Kafka (about 500ms). I think this is somewhat expected, as I'm using `brod:produce_sync` with single messages and expecting all replicas to ack.

I wanted to address this but thought I would ask for advice here on your recommended approach, in terms of efficiency and convenience.

I notice that `brod:produce` accepts a set of messages. I think in that case there would be only one `brod_call_ref` to track, which would be convenient. But I would need to collect the messages by topic before calling `brod:produce`.

I also notice that Brucke tracks the individual `brod_call_ref`s. My app needs to route messages from one inbound topic to several outbound topics, so this might be a more direct mapping of my needs. But while it's perhaps more flexible, there's more tracking to do.

Would these two approaches be about equivalent in terms of efficiency?

Are there other approaches you would recommend?

Thank you for any advice!

**Comment by zmstone** [comment]
`brod:roduce_sync` is the most convenient API to call, but of worse efficiency.
Batching would not solve per-message-set latency, but it would lower the average latency for individual messages.

With regards to batching by brod_producer or the caller?
It's hard to say which is better without knowing the details of your use case.

### Call brod:produce

A typical code structure to batching by brod_producer:
```
% do this block as a init step of your process
% but perhaps not gen_server:init/1 as brod:start_producer may take a few seconds
ok = brod:start_client(...),
ok = brod:start_producer(...), % or make use of the auto_start_producer client config
{ok, Pid} = brod:get_producer(...),
erlang:link(Pid) % if the caller process should/can restart in case of failure on delivery
% erlang:monitor(process, Pid) % otherwise monitor it
```
Then keep track of the `brod_call_ref`:s for each `brod:produce` call.

### Call brod:produce_sync with caller batching

There are many ways to batch by caller,
you can either keep the messages in looping state,
or link-spawn a delegate process: 
```
loop(Acc, Parent, ClientId, Topic, Partition, Timeout) ->
  receive
    {produce, SeqNo, Key, Value} ->
      loop([{Seqno, Key, Value} | Acc], Parent, ClientId, Topic, Partition, Timeout)
  after Timeout when Acc =/= [] ->
    %% Perhaps split up Acc if it's too large
    {LastSeqno, _Key, _Value} = lists:last(Acc),
    ok = brod:produce_sync(ClientId, Topic, Partition, _Key = <<>>, [{K,V} || {_, K, V} <- Acc]),
    Parent ! {ack, LastSeqno}, % to use only one ack
    loop([], Parent, ClientId, Topic, Partition, Timeout)
  end
end
```

### Call brod:produce_sync WITHOUT caller batching

Another option is to make use of `max_linger_ms` and `max_linger_count` producer config
and have many processes calling `brod:produce_sync` (to the same topic-partition) concurrently.
--- this would result in arbitrary message ordering though


brucke used to call brod:produce with batched kv-list as Value, but later we changed to one `brod_call_ref` per message because the downstream Kafka cluster might have a smaller `max-bytes` config. --- This performance degrade (don't have a number) is acceptable to us.

**Comment by objectuser** [comment]
@zmstone That all makes sense to me. The sample code is excellent as well, thank you for providing that.

I didn't really understand `max_linger_ms` etc., but I think I do now.

Thank you very much for your response! 👍
