### ISSUE TITLE
brod_topic_subscriber tries to start reading from the wrong offset if the CommittedOffsets option is used

### ISSUE THREAD

**Issue by shamilpd** [kafka4beam/brod#261]
I am using brod_topic_subscriber and storing the offset of the last processed message (i.e committed offset) in s3. When the consumer restarts the offsets from s3 are passed in the CommittedOffsets options in brod_topic_subscriber.start_link but I am getting "Consumer is suspended" error (https://github.com/klarna/brod/blob/1fe715ea23d354793cc1e51ec622a3ee8f29c9db/src/brod_consumer.erl#L483).
This is because brod is trying to start reading from CommittedOffset + 1 which does not exist yet so you get the offset out of range error from kafka.

Even if CommittedOffset + 1 did exist in kafka, the first message that would come to the consumer after the restart would be have offset CommittedOffset + 2 which means it would skip a message. 

I am getting around this problem by subtracting 1 from the last committed offset and passing that into brod_topic_subscriber.start_link. 

Seems like the +1 [here](https://github.com/klarna/brod/blob/master/src/brod_topic_subscriber.erl#L322) should be removed.

**Comment by zmstone** [comment]
Hi.
This behaviour is indeed incompatible with kafka convention.
and it has been changed in `brod_group_subscriber`, because it commits offsets
together with user-data which can be used to identify old/new version commits,
so we can perform a smooth upgrade when new version code sees old version commits.

however, topic subscriber has no other data associated with offset commit,
this is why we did not try to change it.

nonetheless, it doesn't mean +1 is 'wrong'.
The problem seem to be the wrong offset initialized in s3 as a 'fake' commit.
You can simply commit the `DesieredBeginOffset - 1` instead.

In case the partition is empty, there is no need to initialize a commit,
because `{default_begin_offset, earliest | latest | N}` consumer config can be used instead.
