### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by feapoi** [kafka4beam/brod#390]
$ ./rebar3 compile
===> Verifying dependencies...
    ===> Compiling crc32cer
     DEPEND crc32cer.d
 ERLC   crc32cer.erl
 APP    crc32cer.app.src
 C      crc32c.c
In file included from /cygdrive/h/erl_ws/kafka_client/_build/default/lib/crc32ce
r/c_src/crc32c.c:56:
/cygdrive/h/erl_ws/kafka_client/_build/default/lib/crc32cer/c_src/rdendian.h:143
:2: 茅聰聶猫炉炉茂录職#error Missing definition for be64toh
  143 | #error Missing definition for be64toh
      |  ^~~~~
/cygdrive/h/erl_ws/kafka_client/_build/default/lib/crc32cer/c_src/crc32c.c: 氓聹
篓氓聡陆忙聲掳芒聙聵crc32c_sw芒聙聶盲赂颅:
/cygdrive/h/erl_ws/kafka_client/_build/default/lib/crc32cer/c_src/crc32c.c:113:1
6: 猫颅娄氓聭聤茂录職茅職聬氓录聫氓拢掳忙聵聨氓聡陆忙聲掳芒聙聵le64toh芒聙聶 [-W
implicit-function-declaration]
  113 |         crc ^= le64toh(*(uint64_t *)next);
      |                ^~~~~~~
make: *** [erlang.mk:5808茂录職/cygdrive/h/erl_ws/kafka_client/_build/default/li
b/crc32cer/c_src/crc32c.o] 茅聰聶猫炉炉 1

cygwin compile occur error
environment:
win10 cygwin OTP21.3
----------------------------------------

**Comment by mikpe** [comment]
This would seem to be a problem with crc32cer, which is just a dependency pulled in here.  Please do a standalone build of crc32cer _only_ (not inside brod), and report the build problem at https://github.com/zmstone/crc32cer.  A quick check shows that crc32cer should have support for Cygwin.  I can't easily check myself as it's been many years since I needed to work in Cygwin.

**Comment by feapoi** [comment]
thx
