### ISSUE TITLE
Compression of messages

### ISSUE THREAD

**Issue by dgriff1** [kafka4beam/brod#47]
Hey,

Turns out brod doesnt support gzip/snappy which are part of the kafka wire protocol. I know you are heading towards 2.0. Will this be a feature in there? Do you want the code I wrote to support this? 

I am looking forward to 2.0 and the high level consumer, I ended up writing quite a bit of code to do a simple consumer with the current version.

**Comment by id** [comment]
Hi Dan. This is correct, we have this feature in our TODO, however it was never prioritised because we never got a request for it and don't use compression ourselves. Of course we'll be happy to get a PR for this!

I think 2.0-dev is quite stable right now, try it. @zmstone, what do you think about making it an official 2.0?

**Comment by id** [comment]
Here we go, check out the latest master :)

**Comment by sdball** [comment]
@dgriff1 As a possible interim solution you can setup Kafka brokers to compress all topics:

```
# server.properties
compression.type=snappy
```

By default the brokers defer to the producer to set the compression. With an explicit compression setting the brokers compress all messages using that setting regardless of what the producer used.

Downsides:
- you can't mix compressed and uncompressed topics
- it could be surprising for the compression to not match what the producer used
- the message produced to kafka is uncompressed so you don't save any network usage on the producing side

**Comment by dgriff1** [comment]
Awesome, we will give it a try and I'll see if I can get our compression stuff in a PR.

**Comment by dgriff1** [comment]
@sdball we have mixed compressed/uncompressed messages. They are easy to deal with since attributes=1 is gzip and attributes=2 is snappy. We simply exported the brod_kafka:parse_message_set and pass the gunziped Message.

**Comment by sdball** [comment]
Nice! I look forward to your PR since I could use some compression options as well. :+1:

**Comment by dgriff1** [comment]
Im still working on this, the tests wont run on a Mac due to the docker stuff using "localhost" for everything. The function to decode a message_set seems to have been removed so I am re-adding that.

**Comment by zmstone** [comment]
@dgriff1 the wire format encoding/decoding code has been moved to kafka_protocol.
see kpro.erl and kpro_structs.erl (kpro_structs.erl is generated code)
I haven't looked into the details of compress / decompress, but I suppose it's enough
to add a clause for #kpro_Message{} record in kpro.erl to hijack the call to kpro_structs.erl
i.e. compress before calling kpro_structs:encode
and decompress after kpro_structs:decode

**Comment by zmstone** [comment]
this is a bit more complicated than i thought. @dgriff1 have you started working on it?

**Comment by dgriff1** [comment]
@zmstone mostly ive been trying to figure out how to do it. In kafka_protocol we can change the decoding of the FetchResponsePartition and uncompress for the consumer. I have not looked at doing this for the producer yet. 

Kafka should compress batches of messages but I am getting single compressed messages which is odd. 

Why do you think it will be complicated?

**Comment by zmstone** [comment]
@dgriff1 were your messages produced compressed ?
if messages are produced un-compressed
consumers should never receive compressed messages.

it's more complicated than I thought because I thought it was per-message compression.
turns out the compression is done for a message set, then the compressed message set is
used as the 'value' field of the only one message in a wrapping message set with compression attribute set.

I'm going to start coding, I'll send the pr as soon as I have something ready to push.
we can sync over the code.

**Comment by zmstone** [comment]
by the way, any suggestion on which snappy lib to pick ?

**Comment by dgriff1** [comment]
You can turn on compression in the kafka server.properties by adding 
compression.type = gzip to your server.properties. If you turn on compression and run the test suite you can see the compressed messages.
