### ISSUE TITLE
Why constant UNKNOWN_TOPIC_CACHE_EXPIRE_SECONDS (module brod_client) hard set 120 seconds?

### ISSUE THREAD

**Issue by dbegunkov** [kafka4beam/brod#570]
I observe a strange behavior when there is no topic in Kafka. Topic status is cached. So when it’s created there is a delay up to 120 seconds. This is because of the constant -define(UNKNOWN_TOPIC_CACHE_EXPIRE_SECONDS, 120) in brod_client module. 

Is there any reason why this delay is so high? And could we make it configurable?

**Comment by zmstone** [comment]
Hi @dbegunkov 
Topic re-creation was not taken into account when it was implemented.
The cache was to avoid refreshing metadata too often, also to survive temporary errors like leader unavailable errors etc.

We should probably inspect `Reason` at this line https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L861
and expire immediately if it's `unknown_topic_or_partiton` and expire immediately.

**Comment by dbegunkov** [comment]
Yes - this is also a good option, it seems to me

**Comment by mtvch** [comment]
> We should probably inspect `Reason` at this line
> 
> https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L861
> 
> 
> and expire immediately if it's `unknown_topic_or_partiton` and expire immediately.

Hi @zmstone !
I suspect that the `Reason` will always be `unknown_topic_or_partition`, as this is the only case when an error is inserted into the cache:
1. https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L789
2. https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L804 

I suggest moving `unknown_topic_cache_expire_seconds` to the client configuration so that the default value of `120` seconds can be overridden. This seems like a safer update to me. Would it be okay if I create a PR for it?

**Comment by zmstone** [comment]
> > We should probably inspect `Reason` at this line
> > https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L861
> > 
> > and expire immediately if it's `unknown_topic_or_partiton` and expire immediately.
> 
> Hi @zmstone ! I suspect that the `Reason` will always be `unknown_topic_or_partition`, as this is the only case when an error is inserted into the cache:
> 
> 1. https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L789
> 2. https://github.com/kafka4beam/brod/blob/6966f0244b87904363cb8053ac0364ff281411d9/src/brod_client.erl#L804
> 
> I suggest moving `unknown_topic_cache_expire_seconds` to the client configuration so that the default value of `120` seconds can be overridden. This seems like a safer update to me. Would it be okay if I create a PR for it?

Hi @mtvch 
Yes. PR is very much welcome.
Thank you in advance.
